# Configuration for Predator-Prey with Migration experiments
# Demonstrates AME-ODE on ecological dynamics with spatial heterogeneity

# Model Architecture - optimized for ecological dynamics
model:
  state_dim: 10  # 5 patches × 2 (prey + predator)
  n_experts: 4  # For different ecological regimes
  expert_architecture:
    depth: 5
    width: 128
    activation: "tanh"
    residual: true
    dropout: 0.0
  gating_architecture:
    depth: 3
    width: 64
    activation: "relu"
  history_embedding:
    type: "lstm"
    hidden_dim: 64
    num_layers: 1
  temperature: 0.3  # Sharp routing for ecological regimes
  expert_threshold: 0.2
  # Initialization settings
  use_improved_init: true
  expert_init_strategy: "mixed"
  gating_init_strategy: "uniform"

# Training Configuration
training:
  batch_size: 2048
  learning_rate: 3e-4
  num_epochs: 250  # Longer for seasonal cycles
  early_stopping_patience: 40
  gradient_clip_norm: 5.0
  sequence_length: 100  # Cover multiple seasons
  optimizer: "adam"
  scheduler:
    type: "cosine"
    warmup_epochs: 10
    min_lr: 1e-6
  regularization:
    route_weight: 0.1
    expert_weight: 1e-6
    diversity_weight: 0.0
    smoothness_weight: 0.01  # Important for migration dynamics
    balance_weight: 0.0

# Integration Configuration
integration:
  method: "dopri5"
  rtol: 1e-4
  atol: 1e-6
  max_step_size: 0.1
  min_step_size: 1e-5
  adaptive_step: false
  routing_aware_step: false
  dynamics_max_norm: 50.0

# Data Configuration
data:
  synthetic_systems:
    - name: "predator_prey_migration"
      enabled: true
      n_trajectories: 10000
      trajectory_length: 100  # Multiple seasonal cycles
      sampling_dt: 0.05
      params:
        n_patches: 5  # Spatial patches
        growth_rate: 1.0  # Prey growth
        predation_rate: 1.2  # Predation strength
        conversion_efficiency: 0.6  # Energy transfer
        predator_death: 0.5  # Predator mortality
        prey_migration: 0.1  # Prey movement rate
        predator_migration: 0.05  # Predator movement rate
  noise:
    observation_noise: 0.01
    process_noise: 0.0001  # Environmental stochasticity
  train_val_test_split: [0.6, 0.2, 0.2]
  temporal_sampling: "uniform"
  augmentation:
    random_rotation: false  # Preserve spatial structure
    random_scaling: true  # Vary population sizes

# Computational Resources
compute:
  device: "cuda"
  mixed_precision: false
  gradient_checkpointing: false
  multi_gpu: false
  num_workers: 2

# Logging
logging:
  log_dir: "./logs_predator_prey"
  checkpoint_dir: "./checkpoints_predator_prey"
  tensorboard: true
  wandb:
    enabled: false
  save_frequency: 10
  log_frequency: 10

# Evaluation
evaluation:
  metrics:
    - "trajectory_mse"
    - "computational_efficiency"
    - "expert_specialization"
    - "long_term_stability"
    - "phase_space_geometry"
    - "energy_conservation"  # Population conservation
    - "routing_stability"
  visualization:
    phase_portraits: true
    routing_heatmaps: true
    trajectory_decomposition: true