# Configuration for large-scale system experiments

# Model Architecture - efficient for high dimensions
model:
  n_experts: 8
  expert_architecture:
    depth: 3  # Shallower for efficiency
    width: 512  # Wider networks
    activation: "tanh"  # Better for continuous dynamics (from quick_test)
    residual: true
    dropout: 0.0
  gating_architecture:
    depth: 2
    width: 256
    activation: "relu"
  history_embedding:
    type: "lstm"
    hidden_dim: 128
    num_layers: 1
  temperature: 0.3  # Lower temperature for sharper routing (from quick_test)
  expert_threshold: 0.2  # Higher threshold to force ~2 active experts
  # Initialization settings (from quick_test)
  use_improved_init: true
  expert_init_strategy: "mixed"
  gating_init_strategy: "uniform"

# Training Configuration - optimized for large systems
training:
  batch_size: 256  # Larger batch for stability (balanced with memory)
  learning_rate: 3e-4  # Optimal learning rate from quick_test
  num_epochs: 150
  early_stopping_patience: 20
  gradient_clip_norm: 5.0  # Less restrictive (from quick_test)
  sequence_length: 100
  optimizer: "adam"
  scheduler:
    type: "cosine"  # Better than step (from quick_test)
    warmup_epochs: 10
    min_lr: 1e-6
  regularization:
    route_weight: 0.1  # Moderate routing penalty (from quick_test)
    expert_weight: 1e-6  # Very light L2 (from quick_test)
    diversity_weight: 0.0  # No diversity penalty - let experts specialize
    smoothness_weight: 0.01  # Small smoothness penalty for energy
    balance_weight: 0.0  # Natural specialization

# Integration Configuration
integration:
  method: "rk4"  # Faster than dopri5
  rtol: 1e-4
  atol: 1e-5
  max_step_size: 0.1
  min_step_size: 1e-5
  adaptive_step: true
  routing_aware_step: false  # Disable for speed

# Data Configuration - high-dimensional systems
data:
  synthetic_systems:
    - name: "kuramoto_model"
      enabled: true
      n_trajectories: 5000
      trajectory_length: 100
      sampling_dt: 0.01
      params:
        n_oscillators: [20, 50]
        coupling_strength: [1.0, 4.0]
  noise:
    observation_noise: 0.01
    process_noise: 0.001
  temporal_sampling: "uniform"
  augmentation:
    random_rotation: false
    random_scaling: true
    noise_injection: true
    noise_level: 0.005

# Computational Resources
compute:
  device: "cuda"
  mixed_precision: true  # Enable for efficiency
  gradient_checkpointing: true  # Save memory
  multi_gpu: false
  num_workers: 8

# Evaluation - focus on scalability
evaluation:
  metrics:
    - "trajectory_mse"
    - "computational_efficiency"
    - "expert_specialization"
    - "routing_stability"
  visualization:
    phase_portraits: false  # Skip for high-dim
    routing_heatmaps: true
    trajectory_decomposition: false