# Configuration for Target-Mediated Drug Disposition (TMDD) experiments
# Classic QSP benchmark demonstrating pharmacokinetic heterogeneity

# Model Architecture - optimized for PK/PD dynamics
model:
  state_dim: 4  # Drug, Target, Complex, Internalized
  n_experts: 4  # Different binding/elimination phases
  expert_architecture:
    depth: 5
    width: 128
    activation: "tanh"  # Smooth for concentration dynamics
    residual: true
    dropout: 0.0
  gating_architecture:
    depth: 3
    width: 64
    activation: "relu"
  history_embedding:
    type: "lstm"
    hidden_dim: 64
    num_layers: 1
  temperature: 0.3  # Sharp routing for distinct PK phases
  expert_threshold: 0.2
  # Initialization settings
  use_improved_init: true
  expert_init_strategy: "mixed"
  gating_init_strategy: "uniform"

# Training Configuration
training:
  batch_size: 256
  learning_rate: 3e-4
  num_epochs: 200
  early_stopping_patience: 30
  gradient_clip_norm: 5.0
  sequence_length: 100  # Cover full PK profile
  optimizer: "adam"
  scheduler:
    type: "cosine"
    warmup_epochs: 10
    min_lr: 1e-6
  regularization:
    route_weight: 0.1
    expert_weight: 1e-6
    diversity_weight: 0.0
    smoothness_weight: 0.01  # Smooth PK transitions
    balance_weight: 0.0

# Integration Configuration
integration:
  method: "dopri5"
  rtol: 1e-5  # Tighter for accurate PK
  atol: 1e-7
  max_step_size: 0.1
  min_step_size: 1e-5
  adaptive_step: false
  routing_aware_step: false
  dynamics_max_norm: 50.0

# Data Configuration
data:
  synthetic_systems:
    - name: "tmdd"
      enabled: true
      n_trajectories: 10000
      trajectory_length: 100  # Full PK profile
      sampling_dt: 0.1  # Dense sampling for PK
      params:
        k_elimination: 0.1  # Drug clearance
        k_synthesis: 1.0    # Target synthesis
        k_degradation: 0.2  # Target turnover
        k_on: 0.5          # Binding rate
        k_off: 0.05        # Dissociation
        k_internalization: 0.1  # Complex removal
        IC50_feedback: 10.0  # Feedback strength
        n_hill: 2.0         # Cooperativity
  noise:
    observation_noise: 0.01  # Typical assay noise
    process_noise: 0.0001   # Minimal biological variability
  train_val_test_split: [0.6, 0.2, 0.2]
  temporal_sampling: "uniform"
  augmentation:
    random_rotation: false  # Preserve PK structure
    random_scaling: true    # Vary doses

# Computational Resources
compute:
  device: "cuda"
  mixed_precision: false
  gradient_checkpointing: false
  multi_gpu: false
  num_workers: 2

# Logging
logging:
  log_dir: "./logs_tmdd"
  checkpoint_dir: "./checkpoints_tmdd"
  tensorboard: true
  wandb:
    enabled: false
  save_frequency: 10
  log_frequency: 10

# Evaluation
evaluation:
  metrics:
    - "trajectory_mse"
    - "computational_efficiency"
    - "expert_specialization"
    - "long_term_stability"
    - "phase_space_geometry"
    - "energy_conservation"  # Mass balance in TMDD
    - "routing_stability"
  visualization:
    phase_portraits: true
    routing_heatmaps: true
    trajectory_decomposition: true