# Expert count ablation: K=4 (baseline configuration)
# This is identical to base_multiscale.yml but with explicit naming

!include base_multiscale.yml

# No overrides needed - this is the baseline

# Adjust logging
logging:
  log_dir: "./logs_ablation/experts_k4"
  checkpoint_dir: "./checkpoints_ablation/experts_k4"