# Expert count ablation: K=1 (equivalent to standard Neural ODE)
# Inherits from base_multiscale.yml

!include base_multiscale.yml

# Override for single expert
model:
  n_experts: 1  # Single expert = Neural ODE baseline
  expert_architecture:
    width: 256  # Wider to match total parameter count
  
# No routing needed for single expert
training:
  regularization:
    route_weight: 0.0  # No routing penalty
    balance_weight: 0.0  # No balance needed

# Adjust logging
logging:
  log_dir: "./logs_ablation/experts_k1"
  checkpoint_dir: "./checkpoints_ablation/experts_k1"