# Regularization ablation: No sparsity penalty
# Inherits from base_multiscale.yml

!include base_multiscale.yml

# Override to remove sparsity regularization
training:
  regularization:
    route_weight: 0.0        # No entropy penalty
    expert_weight: 1e-6      # Keep L2
    diversity_weight: 0.0    # Keep no diversity
    smoothness_weight: 0.01  # Keep smoothness
    balance_weight: 0.0      # Keep no balance

# Adjust logging
logging:
  log_dir: "./logs_ablation/reg_no_sparsity"
  checkpoint_dir: "./checkpoints_ablation/reg_no_sparsity"