# Routing ablation: Uniform routing (extremely high temperature)
# Inherits from base_multiscale.yml

!include base_multiscale.yml

# Override for uniform routing
model:
  temperature: 1000.0  # Extremely high temperature for uniform routing
  expert_threshold: 0.0  # All experts always active
  gating_architecture:
    depth: 1  # Minimal network since it won't matter
    width: 16

# Adjust logging
logging:
  log_dir: "./logs_ablation/routing_uniform"
  checkpoint_dir: "./checkpoints_ablation/routing_uniform"