# Routing ablation: State-only routing (minimal history)
# Inherits from base_multiscale.yml

!include base_multiscale.yml

# Override specific settings for state-only routing
model:
  history_embedding:
    type: "lstm"
    hidden_dim: 1  # Minimal history dimension to effectively disable history
    num_layers: 1

# Adjust logging
logging:
  log_dir: "./logs_ablation/routing_state_only"
  checkpoint_dir: "./checkpoints_ablation/routing_state_only"